version: "3.8"

services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    # env_file:
    #   - .env
    restart: always
    volumes:
      - mongo_vol:/data/db
    ports:
      - "7000:27017"

volumes:
  mongo_vol:
